spring:
  config:
    activate:
      on-profile: prd

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ${BUCKET_NAME}
ecard:
  services:
    kakao:
      app-id: 811787
      rest-api-key: 467854698414cdef505d6762cb4fb28c
      js-key: 93163e08f4b978a4f88e07ec6e0ea4bf
    iam:
      x-iam-service-code: HLFS-ECARD
    ebap:
      service-id: e09013c8-1e48-4312-bdd1-7f5c600a4c21
    util:
      url: ecard.ent-bc.com
    coocon:
      publishing-key: 'Jo5h5gJKd2a8p3RA9L62DAhWNQCFpsEe'
      url: wecheck.coocon.co.kr/v1/
      org-code: 'ebc'

checkplus:
  api:
    server-url: 'https://svc.niceapi.co.kr:22001'
  access-token: a174021e-75e9-46ff-bc75-18213fc0ea2e
  product:
    id: 2101979031
  client:
    id: 5ee89aa8-299a-457f-99d0-e4d085671dd1
    secret: d53bf45121af12fac5bff706a4142d2f
