spring:
  config:
    activate:
      on-profile: stg

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ${BUCKET_NAME}
ecard:
  services:
    kakao:
      app-id: 811786
      rest-api-key: 2589f35e2308574e335eea12b57d66be
      js-key: dcf35a51ab104c9f10d9f8937411139b
    iam:
      x-iam-service-code: HLFS-ECARD-STG
    ebap:
      service-id: 95b60deb-fea0-4dfe-9e6c-4b222c28db8d
    util:
      url: stg.ecard.ent-bc.com
    coocon:
      publishing-key: 'Jo5h5gJKd2a8p3RA9L62DAhWNQCFpsEe'
      url: devwc.coocon.co.kr/v1/
      org-code: 'ebc'

checkplus:
  api:
    server-url: 'https://svc.niceapi.co.kr:22001'
  access-token: a174021e-75e9-46ff-bc75-18213fc0ea2e
  product:
    id: 2101979031
  client:
    id: 5ee89aa8-299a-457f-99d0-e4d085671dd1
    secret: d53bf45121af12fac5bff706a4142d2f
